src/Entity/Book.php
<?php

namespace App\Entity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use App\Repository\BookRepository;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Author;
use App\Entity\Category;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use DateTime;


/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 * @ORM\Table(name="books",uniqueConstraints={@ORM\UniqueConstraint(name="unique_isbn", columns={"isbn"})})
 * @Vich\Uploadable
 * @UniqueEntity("Isbn")
 */
class Book
{
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Positive
     */
    private $Isbn;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Img_url;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $length;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $topcis;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="books")
     * @ORM\JoinColumn(nullable=false,onDelete="CASCADE")
     * @Assert\NotBlank
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity=Author::class, inversedBy="books")
     * @ORM\JoinColumn(nullable=false,onDelete="CASCADE")
     * @Assert\NotBlank
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="book")
     */
    private $comments;

    /**
     * @ORM\Column(type="string", length=255)
     * Assert\NotBlank
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     */
    private $file_url;


    /**
     * simple property to upload file
     * 
     * @Vich\UploadableField(mapping="books_files", fileNameProperty="file_url")
     * 
     * @Assert\File(
     *     maxSize = "10M",
     *     mimeTypes = {"application/pdf", "application/x-pdf"},
     *     mimeTypesMessage = "Please upload a valid PDF "
     * )
     * 
     * @var File|null
     */
    private $bookFile;

    /**
     * * simple property to upload image
     * * @Vich\UploadableField(mapping="books_images", fileNameProperty="Img_url")
     *   @Assert\Image(
     *     maxSize = "10M",
     *     mimeTypes = {"image/jpg", "image/jpeg","image/png"},
     *     mimeTypesMessage = "Please upload a valid Format"
     * 
     * )
     */
    private $bookImage;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

  



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsbn(): ?string
    {
        return $this->Isbn;
    }

    public function setIsbn(string $Isbn): self
    {
        $this->Isbn = $Isbn;

        return $this;
    }

    public function getImgUrl(): ?string
    {
        return $this->Img_url;
    }

    public function setImgUrl(?string $Img_url): self
    {
        $this->Img_url = $Img_url;

        return $this;
    }

    public function getFileUrl()
    {
        return $this->file_url;
    }   

    public function setFileUrl(?string $file_url): self
    {
        $this->file_url = $file_url;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLength(): ?int
    {
        return $this->length;
    }

    public function setLength(int $length): self
    {
        $this->length = $length;

        return $this;
    }

    public function getTopcis(): ?string
    {
        return $this->topcis;
    }

    public function setTopcis(?string $topcis): self
    {
        $this->topcis = $topcis;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getAuthor(): ?Author
    {
        return $this->author;
    }

    public function setAuthor(?Author $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setBook($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getBook() === $this) {
                $comment->setBook(null);
            }
        }

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

 

     /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $bookFile
     */
    public function setBookFile(?File $bookFile = null): void
    {
        $this->bookFile = $bookFile;
     
        if (null !== $bookFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getBookFile(): ?File
    {
        return $this->bookFile;
    }

    public function setBookImage(?File $bookImage= null): void
    {
        $this->bookImage = $bookImage;

        if (null !== $bookImage) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getBookImage(): ?File
    {
        return $this->bookImage;
    }

     /**
     * @var DateTime $created
     *
     * @ORM\Column(name="created_at", type="datetime", nullable=true)
     */
    protected $createdAt;

    /**
     * @var DateTime $updated
     *
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     */
    protected $updatedAt;

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function updatedTimestamps(): void
    {
        $dateTimeNow = new DateTime('now');

        $this->setUpdatedAt($dateTimeNow);

        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt($dateTimeNow);
        }
    }

    public function getCreatedAt() :?DateTime
    {
        return $this->createdAt;
    }
    
    public function setCreatedAt(DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt() :?DateTime
    {
        return $this->updatedAt;
    }
    
    public function setUpdatedAt(DateTime $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    
}

templates/website/pages/book-detail.html.twig
{% extends 'website/base.html.twig' %}

{% block body %}
	{% include 'website/includes/page-banner.html.twig' with {'title': book.title ,'subtitle':book.description} %}
	   {{ render(controller('App\\Controller\\BookController::search',{'withResult':false}))  }}
	<!-- Start: Products Section -->
	<div id="content" class="site-content">
		<div id="primary" class="content-area">
			<main id="main" class="site-main">
				<div class="booksmedia-detail-main">
					<div class="container">
						<div class="row"></div>
						<div class="row">
							<div class="col-md-12 ">
								<div class="booksmedia-detail-box">
									<div class="single-book-box">
										<div class="post-thumbnail">

											{% if ('http://' in book.Imgurl) or ('https://' in  book.Imgurl) %}
												{% set path = book.Imgurl %}
											{% else  %}
												{% set path = vich_uploader_asset(book,'bookImage')  %}
											{% endif %}
											<img alt="Book" src="{{ path }}"/>
										</div>
										<div class="post-detail">


											<header class="entry-header">
												<h2 class="entry-title">{{ book.title }}</h2>
												<ul>
													<li>
														<strong>Author:</strong>
														{{ book.author.fullname }}</li>
													<li>
														<strong>ISBN:</strong>
														{{ book.Isbn }}</li>

													<li>
														<strong>Length:</strong>
														{{ book.length }}</li>
													<li>
														<strong>Format:</strong>
														PDF</li>

													<li>
														<strong>Genre :</strong>
														{{ book.category.name }}</li>
													<li>
														<strong>Topics:</strong>
														{{ book.topcis }}
													</li>

												</ul>
											</header>
											<div class="entry-content post-buttons">
												{% if ('http://' in book.fileUrl) or ('https://' in  book.fileUrl) %}
													{% set filePath = book.fileUrl %}
												{% else  %}
													{% set filePath = vich_uploader_asset(book,'bookFile') %}
												{% endif %}
												<td>
													<a href="{{ filePath }}" class="btn btn-dark-gray" download="">Download</a>
												</td>
											</div>
										</div>
									</div>
									<p>
										<strong>Summary:</strong>
										{{ book.description }}
									</p>
									<!-- Comment Section -->
									<div>
										<h2 class="section-title text-center">Comments</h2>
										<div class="comments-area" id="comments">
											<div class="comment-bg">
												<h4 class="comments-title">User Comments</h4>
												<span class="underline left"></span>
												<ol class="comment-list">
													{% for comment in book.comments %}
														<li class="comment even thread-even depth-1 parent">
															<div class="comment-body">
																<div class="comment-author vcard">
																	<img class="avatar avatar-32 photo avatar-default" src="{{ asset('assets/images/avatar.jpg') }}" alt="Comment Author">
																	<b class="fn">
																		<a class="url" rel="external nofollow" href="#">{{ comment.username }}</a>
																	</b>
																</div>
																<footer class="comment-meta">
																	<div class="left-arrow"></div>

																	<div class="comment-metadata">
																		<a href="#">
																			<time datetime="2016-01-17">
																				<b>{{ comment.email }}</b>
																			</time>
																		</a>
																	</div>
																	<div class="comment-content">
																		<p>
																			{{ comment.description }}
																		</p>
																	</div>
																</footer>
															</div>

														</li>
													{% endfor %}
												</ol>
											</div>

										</div>
										{{ form_start(form) }}
										{{ form_widget(form) }}
										<input type="hidden" id="book-id" name="book_id" value="{{ book.Id }}"/>
										<button class="btn btn-primary d-block mx-auto">WRITE YOUR COMMENT:</button>
										{{ form_end(form) }}
									</div>

								</div>
							</div>

						</div>
					</div>
				</div>
			</main>
		</div>
	</div>
	<!-- End: Products Section -->
{% endblock %}

templates/website/pages/books.html.twig
{% extends 'website/base.html.twig' %}

{% block body %}
	{% include 'website/includes/page-banner.html.twig' with {'title':'Home'} %}
       {{ render(controller('App\\Controller\\BookController::search',{'withResult':true}))  }}

{% endblock %}

templates/website/pages/category.html.twig
{% extends 'website/base.html.twig' %}

{% block body %}
     {% include 'website/includes/page-banner.html.twig' with {'title': 'Category','subtitle':category.name} %}
       {{ render(controller('App\\Controller\\BookController::search',{'withResult':false}))  }}
     <div id="content" class="site-content">
        <div class="books-full-width">
            <div class="container">
                {% include 'bundles/knp_paginator/sort.html.twig' %}
                <div class="booksmedia-fullwidth">
                
                                            <ul>
                                                {% for book in books %}
                                                <li>
                                                   
                                                    <figure>
                                                        <a href="{{ path('book.show',{'slug':book.slug}) }}">
                                                        
                                                          {% if ('http://' in book.Imgurl) or ('https://' in  book.Imgurl) %}
                                                            {% set path = book.Imgurl %}
                                                          {% else  %}
                                                            {% set path = vich_uploader_asset(book,'bookImage')  %}
                                                          {% endif %}
                                                        <img src="{{ path }}" alt="{{ book.title }}" >
                                                        
                                                        </a>
                                                        <figcaption>
                                                            <header>
                                                                <h4><a href="{{ path('book.show',{'slug':book.slug}) }}">{{ book.title }}</a></h4>
                                                                <p><strong>Author:</strong>  {{ book.author.fullname }}</p>
                                                                <p><strong>ISBN:</strong>  {{ book.Isbn }}</p>
                                                                <p><strong>Length:</strong>  {{ book.length }}</p>
                                                            </header>
                                                            <p>{{ book.description }}</p>
                                                            <div class="actions">
                                                                <ul>
                                                                    <li>
                                                                        <a href="{{ path('book.show',{'slug':book.slug}) }}"  data-toggle="blog-tags" data-placement="top" title="More Info">
                                                                            <i class="fa fa-info-circle"></i>
                                                                        </a>
                                                                    </li>
                                                                   
                                                                </ul>
                                                            </div>
                                                        </figcaption>
                                                    </figure>                                                
                                                </li>                            
                                                {% endfor %}
                                            </ul>
                                        </div>
                                        {{ knp_pagination_render(books,'',{'align':'center'}) }}
                                   
                                    </div>
                            
                                </div>
                            </main>
                        </div>
                    </div>
                    <!-- End: Products Section -->
                </div>
            </div>
        </div>

        

{% endblock %}

templates/website/pages/home.html.twig
{% extends 'website/base.html.twig' %}

{% block body %}
	{% include 'website/includes/page-banner.html.twig' with {'title':'Home'} %}

    {{ render(controller('App\\Controller\\BookController::search',{'withResult':false}))  }}

	<!-- Start: Welcome Section -->
	<section class="welcome-section">
		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<div class="welcome-wrap">
						<div class="welcome-text">
							<h2 class="section-title">Welcome to Tech Books</h2>
							<span class="underline left"></span>
							<p class="lead">The standard chunk of Lorem Ipsum used since</p>
							<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humor, or randomized words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humor, or non-characteristic words etc.</p>

						</div>
					</div>
				</div>
				<div class="col-md-3">
					<div class="facts-counter">
						<ul>
							<li class="bg-light-green">
								<div class="fact-item">
									<div class="fact-icon">
										<i class="ebook"></i>
									</div>
									<span>Books<strong class="fact-counter">{{ nb_books }}
										</strong>
									</span>
								</div>
							</li>

						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="welcome-image"></div>
	</section>
	<!-- End: Welcome Section -->
	<section class="section-padding">
		<div class="container">
         <h2 class="text-center text-secondary">All Books</h2>
			<div class="booksmedia-fullwidth">
               
				<ul>
					{% for book in books %}
						<li>

							<figure>
								<a href="{{ path('book.show',{'slug':book.slug}) }}">

									{% if ('http://' in book.Imgurl) or ('https://' in  book.Imgurl) %}
										{% set path = book.Imgurl %}
									{% else  %}
										{% set path = vich_uploader_asset(book,'bookImage')  %}
									{% endif %}
									<img src="{{ path }}" alt="{{ book.title }}">

								</a>
								<figcaption>
									<header>
										<h4>
											<a href="{{ path('book.show',{'slug':book.slug}) }}">{{ book.title }}</a>
										</h4>
										<p>
											<strong>Author:</strong>
											{{ book.author.fullname }}</p>
										<p>
											<strong>ISBN:</strong>
											{{ book.Isbn }}</p>
										<p>
											<strong>Length:</strong>
											{{ book.length }}</p>
									</header>
									<p>{{ book.description }}</p>
									<div class="actions">
										<ul>
											<li><ahref="{{path('book.show',{'slug':book.slug})}}" data-toggle="blog-tags" data-placement="top" title="More Info"><i class="fa fa-info-circle"></i></a></li>

										</ul>
									</div>
								</figcaption>
							</figure>
						</li>
					{% endfor %}
				</ul>
			</div>
			{{ knp_pagination_render(books,'',{'align':'center'}) }}

		</div>
	</div>

</div></main></div></div></div><!-- End: Products Section -->{% endblock %}